Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job               count
--------------  -------
all                   1
call                  1
merge_coverage        1
merge_freq            1
samtools_index        1
total                 5

Select jobs to execute...

[Thu Aug 29 12:36:14 2024]
rule call:
    input: data/reference_index/REJOc-reference.fa, data/sorted_reads/CD00-m000-00-REJOc.bam, data/bed_file/REJOc.bed
    output: data/calls/CD00-m000-00-REJOc.csv, data/coverage/CD00-m000-00-REJOc.csv
    jobid: 11
    reason: Missing output files: data/calls/CD00-m000-00-REJOc.csv, data/coverage/CD00-m000-00-REJOc.csv
    wildcards: sample=CD00-m000-00-REJOc
    resources: tmpdir=/var/folders/k0/3b7hrv0d2n7fs2g57vkng1fm0000gp/T

[Thu Aug 29 12:36:15 2024]
Error in rule call:
    jobid: 11
    input: data/reference_index/REJOc-reference.fa, data/sorted_reads/CD00-m000-00-REJOc.bam, data/bed_file/REJOc.bed
    output: data/calls/CD00-m000-00-REJOc.csv, data/coverage/CD00-m000-00-REJOc.csv

RuleException:
CalledProcessError in file /Users/anitido/Documents/GitHub/Escapability/Viral Escape Analysis/Snakefile, line 108:
Command 'set -euo pipefail;  /Users/anitido/miniforge3/envs/viral_escape/bin/python3.10 '/Users/anitido/Documents/GitHub/Escapability/Viral Escape Analysis/.snakemake/scripts/tmp7d26_7ou.codon_caller.py'' returned non-zero exit status 1.
  File "/Users/anitido/Documents/GitHub/Escapability/Viral Escape Analysis/Snakefile", line 108, in __rule_call
  File "/Users/anitido/miniforge3/envs/viral_escape/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-08-29T123614.149960.snakemake.log
